### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by meoso** [betaflight/blackbox-log-viewer#340]
I was able to compile 'release' in the past weeks, tried today with these issues:

```
 $ git pull ; gulp release --linux64
Already up to date.
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-yarn'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/media/disk2/SYNC/XPS/blackbox-log-viewer/gulpfile.js:19:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)


 $ npm install gulp-yarn
npm notice created a lockfile as package-lock.json. You should commit this file.
+ gulp-yarn@2.0.0
added 2 packages from 4 contributors and removed 262 packages in 15.704s


 $ git pull ; gulp release --linux64
Already up to date.
[08:20:11] Local gulp not found in /media/disk2/SYNC/XPS/blackbox-log-viewer
[08:20:11] Try running: npm install gulp


 $ npm install gulp
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ gulp@4.0.2
added 254 packages from 170 contributors in 21.403s


 $ git pull ; gulp release --linux64
Already up to date.
module.js:550
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/media/disk2/SYNC/XPS/blackbox-log-viewer/gulpfile.js:10:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)


```

**Comment by meoso** [comment]
fixed: `npm install del` missed that one, sorry
